title: Sajith Udurawana - Front-End Technology Consutant
description: Senior Web/Mobile Developer | Technology Consultant for startups (React, React Native, Flutter, Cordova)
baseurl: ""
url: "https://sajith-udurawana.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
